### ISSUE TITLE
Add Sorting to volunteer list page

### ISSUE THREAD

**Issue by dherbst** [ncosd/food-pantry-app#171]
# Description
Add sorting to the volunteer list component on the volunteer list page.

## Sorting
- [ ] Firstname
- [ ] Lastname
- [ ] email
- [ ] Updated

# Expected solution
Modify the list component

**Comment by dherbst** [comment]
Added https://github.com/dherbst/food-pantry-app/commit/da843429578c30934f76c84c360bf8d8a5107b68 to initially sort by first name.

**Comment by sahilmulla** [comment]
Does this need directional sorting?

**Comment by dherbst** [comment]
If you mean clicking to toggle ascending and descending, yes.  Please add directional sorting.
