### ISSUE TITLE
Check for attending volunteer windows when choosing unavailable date

### ISSUE THREAD

**Issue by dherbst** [ncosd/food-pantry-app#203]
# Feature Description

On the unavailability page, when you choose the date range, search to see if the user is attending a volunteer window during the unavailability date range.  If so, put up a warning, and the link to cancel the attending.

- [ ] displays volunteer windows you are signed up for during the start/end date

# Expected solution

# Testing

**Comment by Lukada-taiya** [comment]
Please assign this to me.

**Comment by dherbst** [comment]
@Lukada-taiya ok, if you want it, go ahead.  Let me know if you have any questions.
