### ISSUE TITLE
Add Release Notes page for the guest app

### ISSUE THREAD

**Issue by dherbst** [ncosd/food-pantry-app#246]
# Feature Description

Add a release notes page similar to https://github.com/ncosd/food-pantry-app/blob/main/web/admin/src/views/ReleaseNotesPage.vue in the guest app.

# Expected solution

Add the page in https://github.com/ncosd/food-pantry-app/blob/main/web/app/src/views/
Add the route to the page
Link the version number in the page footer to the release notes anchor in the release notes page similar to how it is done in the admin app.

# Testing

Clicking the version number in the page footer takes you to the release notes page.

**Comment by rakshitriya** [comment]
@dherbst , can I work on this?

**Comment by dherbst** [comment]
@rakshitriya yes, go for it!

**Comment by rakshitriya** [comment]
Hi, I have defined the variable in .env file, however, I am getting this:

```
 VITE v4.3.9  ready in 488 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
(!) %VITE_PROJECT_LONG_NAME% is not defined in env variables found in /index.html. Is the variable mistyped?
```

**Comment by dherbst** [comment]
Double check the `.env` file is in `web/app/.env`.    

The `.env` file should look similar to the file https://github.com/ncosd/food-pantry-app/blob/main/web/app/env.demo

**Comment by rakshitriya** [comment]
I am still not able to set it up, with the same error.

pasting here the .env files

<img width="954" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/50b6890b-9d1b-4e16-b148-070abcea9ede">

<img width="949" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/2a74e96f-c7db-4845-bf7a-25c3c4b09f7e">

<img width="957" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/7a1f6bfd-cad0-474a-9ed3-9be63e95b3f1">

<img width="410" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/1d9bf2a6-0e6b-459f-b63d-9f210b68361e">

<img width="406" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/2725df73-e40a-409a-b02b-043fed286682">

and then 

```
#from  web/app directory
npm run serve:firebase:emulator 
npm run dev                      
```

Does this setup look fine to you?  I didn't understand `firebase use dev` command because it said that the project didn't exist, so I used `firebase use food-pantry-app-os`.

Please let me know if you'd require any more information to debug this.

Thanks,
Riya

**Comment by dherbst** [comment]
The first `.env` file in the first image, it is in `web/app/src/.env`.  Move it up one folder to `web/app/.env` and that should fix the problem.

**Comment by rakshitriya** [comment]
That is helpful! 

I know this is sad but there's another issue: The server doesn't respond anything. It's a blank homepage -

<img width="504" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/0e125521-f110-4b52-9bba-1dd9cb1eaa36">

I looked up this https://stackoverflow.com/questions/56158010/firestore-firebase-emulator-not-running, but found that the files - `firebase.json`, `firestore.rules` and `firestore.indexes.json` exist inside  web folder.

Am I missing out on something?

**Comment by dherbst** [comment]
Yes, sorry the instructions said to put the variables in the `.env.dev` file - but they should be copied into the `web/app/.env` file and the `web/admin/.env` files instead. 

Try moving the contents of the file in `web/functions/.env.dev` so they are in the `web/app/.env` file and copy them from `web/admin/.env.dev` into `web/admin/.env`

I've made a change to the instructions to reflect this in this commit: https://github.com/ncosd/food-pantry-app/commit/a9bf655909337c3201687efa699dbc34a3caf98f

**Comment by dherbst** [comment]
And the firebase files are in the correct folder, yes.

**Comment by dherbst** [comment]
@rakshitriya are you still working on this?  If not, I have time to finish it up.

**Comment by rakshitriya** [comment]
Hey, yes I have been trying to set it up. Give me a day Or two more, else
you can pick if up. The page still shows blank.

**Comment by dherbst** [comment]
@rakshitriya take another look at the https://github.com/ncosd/food-pantry-app?tab=readme-ov-file#setup in the readme - I changed the "Prepare the `.env` files" section to correct an error since you first looked at it.   Maybe start a fresh clone would help.

**Comment by rakshitriya** [comment]
The page looks like:

<img width="783" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/25d58281-c915-4595-8aad-c8b510423795">

Is this expected?

These are the files which didn't load:

<img width="957" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/f8f08c8e-0862-4e2c-a4c3-48d53c073e9f">

**Comment by dherbst** [comment]
> Is this expected?

Yes!  It looks like you have it up and running.   Those errors are expected when you run with the local emulator.

**Comment by rakshitriya** [comment]
Glad I could make it, please let me know if there's any issue with the PR 😀
