### ISSUE TITLE
Add sorting to TaskTypes admin page

### ISSUE THREAD

**Issue by dherbst** [ncosd/food-pantry-app#274]
# Feature Description

The table headers should be sortable like the volunteer list is sortable.

# Expected solution

Implement the same sorting as the volunteer list page on the tasktypes page.

# Testing

**Comment by nishit-prasad** [comment]
New contributor here: can this be assigned to me, please? I'd like to work on this.

**Comment by dherbst** [comment]
Yes, go for it!
