### ISSUE TITLE
Add sorting to the column headers on the locations page

### ISSUE THREAD

**Issue by dherbst** [ncosd/food-pantry-app#275]
# Feature Description

The locations page column headers should be sortable like the volunteers list page is sortable.

# Expected solution

Add clickable sorting headers to the locations page headers.

# Testing

**Comment by Lukada-taiya** [comment]
Please assign this to me. This will be a good start

**Comment by dherbst** [comment]
@Lukada-taiya go for it!  Remember to base your PR from the dev-1.12.0 branch.

**Comment by Lukada-taiya** [comment]
Ok. Sure
