### ISSUE TITLE
Add dark/light theme chooser to guest app header

### ISSUE THREAD

**Issue by dherbst** [ncosd/food-pantry-app#278]
# Feature Description

The volunteer application has a dark/light theme chooser component in the navbar header.  This should be moved to a common component directory, and added to the `vite.config.js` file.  

# Expected solution

- [ ] Create common component directory to hold components in both apps
- [ ] Add the common component directory to the `vite.config.js` resolve alias section so it can found in both apps, guest and admin.
- [ ] Test that both apps work as expected and theme can be chosen.

# Testing

**Comment by nishit-prasad** [comment]
New contributor here: can this be assigned to me, please? I'd like to work on this.

**Comment by dherbst** [comment]
Yes, go for it!

**Comment by dherbst** [comment]
Fixed in 1.16.0
