### ISSUE TITLE
Enhancement: Add v-bind key attribute to all Instances of Vue Loops

### ISSUE THREAD

**Issue by Lukada-taiya** [ncosd/food-pantry-app#285]
# Feature Description

We are currently looping through records from firestore without passing unique key attributes to differentiate each record. This may work well in most cases, but it could lead to:
- Potential Bugs: Vue relies on keys to efficiently update the DOM and maintain component state, so not providing them might introduce inconsistencies or errors.
- Unpredictable Behaviour: Without unique keys, Vue may have difficulty distinguishing between different elements, leading to unexpected behavior in certain situations. 
- Performance issues: Without a key, Vue might have to recreate and reorder the DOM elements every time the list changes. This can result in decreased performance, especially when dealing with large lists, as it becomes less efficient to track and update each element.

# Expected solution

Add v-bind key attribute to uniquely differentiate different records being loop through.
More here:
[Vue Documentation](https://vuejs.org/guide/essentials/list#maintaining-state-with-key)

# Testing

**Comment by dherbst** [comment]
The ones where a key is available are used, closing.
