### ISSUE TITLE
Create a way for users to verify their email addresses

### ISSUE THREAD

**Issue by dherbst** [ncosd/food-pantry-app#39]
# Feature Description

Decide if during the registration flow we want to make sure the user verifies their email address, or if we want to have a link from the user profile page.

# Expected solution

Use https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email to send the verification email.

In the AppNavigation component, create an EmailVerified component which displays if the user is not verified.  It should have a link to the user profile page, where they can click a link to have the verification email re-sent to them.

# Testing

**Comment by sahilmulla** [comment]
@dherbst can I work on this?

**Comment by dherbst** [comment]
@sahilmulla yes, go for it!

**Comment by sahilmulla** [comment]
this needs to be done for admin/AppNavigation or app/AppNavigation @dherbst

**Comment by dherbst** [comment]
The admin one.
